require("dotenv").config();
const mongoose = require("mongoose");
const cloudinary = require("./utils/cloudinary");
const Guide = require("./models/GuideApplication");

const guides = [
  {
    name: "Nikhil Domade",
    email: "guide1@example.com",
    phone: "9876500001",
    department: "Information Technology",
    year: 4,
    city: "Pune",
    taluka: "Shivajinagar",
    state: "Maharashtra",
    country: "India",
    gender: "Male",
    role: "Guide",
    pay: 1500,
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d",
  },
  {
    name: "Priya Desai",
    email: "guide2@example.com",
    phone: "9876500002",
    department: "Computer Engineering",
    year: 3,
    city: "Mumbai",
    taluka: "Andheri",
    state: "Maharashtra",
    country: "India",
    gender: "Female",
    role: "Guide",
    pay: 1400,
    imageUrl: "https://images.unsplash.com/photo-1494790108755-2616b34e4178",
  },
  {
    name: "Amit Sharma",
    email: "guide3@example.com",
    phone: "9876500003",
    department: "Mechanical Engineering",
    year: 4,
    city: "Nagpur",
    taluka: "Sitabuldi",
    state: "Maharashtra",
    country: "India",
    gender: "Male",
    role: "Guide",
    pay: 1600,
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e",
  },
  {
    name: "Sneha Patil",
    email: "guide4@example.com",
    phone: "9876500004",
    department: "Electrical Engineering",
    year: 3,
    city: "Thane",
    taluka: "Kalwa",
    state: "Maharashtra",
    country: "India",
    gender: "Female",
    role: "Guide",
    pay: 1350,
    imageUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80",
  },
  {
    name: "Vikram Jadhav",
    email: "guide5@example.com",
    phone: "9876500005",
    department: "Civil Engineering",
    year: 4,
    city: "Nashik",
    taluka: "Sinnar",
    state: "Maharashtra",
    country: "India",
    gender: "Male",
    role: "Guide",
    pay: 1450,
    imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
  },
  {
    name: "Anjali Mehta",
    email: "guide6@example.com",
    phone: "9876500006",
    department: "Electronics",
    year: 3,
    city: "Aurangabad",
    taluka: "CIDCO",
    state: "Maharashtra",
    country: "India",
    gender: "Female",
    role: "Guide",
    pay: 1200,
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
  },
  {
    name: "Rohit Kulkarni",
    email: "guide7@example.com",
    phone: "9876500007",
    department: "IT",
    year: 4,
    city: "Solapur",
    taluka: "North Solapur",
    state: "Maharashtra",
    country: "India",
    gender: "Male",
    role: "Guide",
    pay: 1550,
    imageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7",
  },
  {
    name: "Neha Joshi",
    email: "guide8@example.com",
    phone: "9876500008",
    department: "Computer Engineering",
    year: 2,
    city: "Kolhapur",
    taluka: "Karveer",
    state: "Maharashtra",
    country: "India",
    gender: "Female",
    role: "Guide",
    pay: 1300,
    imageUrl: "https://images.unsplash.com/photo-1614283233556-f35b0c801ef1",
  },
  {
    name: "Siddharth Verma",
    email: "guide9@example.com",
    phone: "9876500009",
    department: "Mechanical",
    year: 4,
    city: "Satara",
    taluka: "Wai",
    state: "Maharashtra",
    country: "India",
    gender: "Male",
    role: "Guide",
    pay: 1700,
    imageUrl: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91",
  },
  {
    name: "Pooja Chavan",
    email: "guide10@example.com",
    phone: "9876500010",
    department: "Electronics and Telecommunication",
    year: 3,
    city: "Amravati",
    taluka: "Badnera",
    state: "Maharashtra",
    country: "India",
    gender: "Female",
    role: "Guide",
    pay: 1400,
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
  },
  {
    name: "Kunal More",
    email: "guide11@example.com",
    phone: "9876500011",
    department: "IT",
    year: 4,
    city: "Beed",
    taluka: "Majalgaon",
    state: "Maharashtra",
    country: "India",
    gender: "Male",
    role: "Guide",
    pay: 1500,
    imageUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61",
  },
  {
    name: "Sakshi Nair",
    email: "guide12@example.com",
    phone: "9876500012",
    department: "CE",
    year: 4,
    city: "Palghar",
    taluka: "Vasai",
    state: "Maharashtra",
    country: "India",
    gender: "Female",
    role: "Guide",
    pay: 1250,
    imageUrl: "https://images.unsplash.com/photo-1551836022-deb4988cc6c0",
  },
  {
    name: "Yash Gandhi",
    email: "guide13@example.com",
    phone: "9876500013",
    department: "EE",
    year: 3,
    city: "Nanded",
    taluka: "Kinwat",
    state: "Maharashtra",
    country: "India",
    gender: "Male",
    role: "Guide",
    pay: 1550,
    imageUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde",
  },
  {
    name: "Divya Rane",
    email: "guide14@example.com",
    phone: "9876500014",
    department: "ME",
    year: 4,
    city: "Jalgaon",
    taluka: "Chalisgaon",
    state: "Maharashtra",
    country: "India",
    gender: "Female",
    role: "Guide",
    pay: 1450,
    imageUrl: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39",
  },
  {
    name: "Ajay Thakur",
    email: "guide15@example.com",
    phone: "9876500015",
    department: "Civil",
    year: 4,
    city: "Latur",
    taluka: "Udgir",
    state: "Maharashtra",
    country: "India",
    gender: "Male",
    role: "Guide",
    pay: 1500,
    imageUrl: "https://images.unsplash.com/photo-1552374196-1ab2a1c59350",
  },
  {
    name: "Isha Kamat",
    email: "guide16@example.com",
    phone: "9876500016",
    department: "IT",
    year: 4,
    city: "Ratnagiri",
    taluka: "Chiplun",
    state: "Maharashtra",
    country: "India",
    gender: "Female",
    role: "Guide",
    pay: 1350,
    imageUrl: "https://images.unsplash.com/photo-1607746882042-944635dfe10e",
  },
  {
    name: "Omkar Sawant",
    email: "guide17@example.com",
    phone: "9876500017",
    department: "Computer Engineering",
    year: 4,
    city: "Ahmednagar",
    taluka: "Pathardi",
    state: "Maharashtra",
    country: "India",
    gender: "Male",
    role: "Guide",
    pay: 1600,
    imageUrl: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91",
  },
  {
    name: "Ritika Kale",
    email: "guide18@example.com",
    phone: "9876500018",
    department: "Electronics",
    year: 3,
    city: "Dhule",
    taluka: "Shirpur",
    state: "Maharashtra",
    country: "India",
    gender: "Female",
    role: "Guide",
    pay: 1400,
    imageUrl: "https://images.unsplash.com/photo-1521146764736-56c929d59c83",
  },
  {
    name: "Harshad Bhise",
    email: "guide19@example.com",
    phone: "9876500019",
    department: "Mechanical Engineering",
    year: 4,
    city: "Chandrapur",
    taluka: "Ballarpur",
    state: "Maharashtra",
    country: "India",
    gender: "Male",
    role: "Guide",
    pay: 1650,
    imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
  },
  {
    name: "Tanvi Deshmukh",
    email: "guide20@example.com",
    phone: "9876500020",
    department: "IT",
    year: 4,
    city: "Yavatmal",
    taluka: "Digras",
    state: "Maharashtra",
    country: "India",
    gender: "Female",
    role: "Guide",
    pay: 1450,
    imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9",
  },
];

async function seedGuides() {
  await mongoose.connect(
    "mongodb+srv://domadenikhil:1uooV4uCIDKWipHz@cluster0.o8k3ye6.mongodb.net/test?retryWrites=true&w=majority&appName=Cluster0"
  );

  console.log("Connected to DB");

  for (const guide of guides) {
    const uploaded = await cloudinary.uploader.upload(guide.imageUrl, {
      folder: "guide_uploads",
      resource_type: "image",
    });

    await Guide.create({
      ...guide,
      image: uploaded.secure_url,
    });

    console.log(`Guide ${guide.name} added with Cloudinary image`);
  }

  console.log("All guides seeded ✅");
  mongoose.disconnect();
}

seedGuides().catch((err) => console.error(err));
